export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_RECIEVED = "EVENT/METRICS_RECEIVED";
export const METRIC_LIST_RECEIVED = "EVENT/METRIC_LIST_RECIEVED";
export const FETCH_MEASURMENTS = 'EVENT/FETCH_MEASURMENTS';
export const MEASURMENTS_RECEIVED = "EVENT/MEASURMENTS_RECIEVED";
export const METRIC_CHOICE_RECEIVED = "EVENT/METRIC_CHOICE_RECIEVED";
export const METRIC_SELECTED = "EVENT/METRIC_SELECTED";